name: CI-CD

on:
  push:
    branches: ["main"]

jobs:
  build-js-css:
    name: Build JS and CSS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PUSH_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - run: npm install
      - run: npm run production

      - name: Commit assets
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -B deploy
          git add -f public/
          git commit -m "build: github actions auto assets deployment"
          git push -f origin deploy

      - name: Deploy to production server
        uses: appleboy/ssh-action@master
        with:
          username: root
          host: "192.81.216.170"
          key: ${{ secrets.SSH_PASSWORD }}
          script: "cd /var/www/html/devknife && sh server_deploy.sh"
